-- Phigros 自制谱面比赛报名系统 Supabase 初始化脚本
-- 在 Supabase Dashboard -> SQL Editor 中执行。
-- 执行后请：
-- 1. 在 Authentication -> Users 创建管理员用户。
-- 2. 将管理员 user id 写入 public.admins 表。
-- 3. 在前端 config.js 填入 Project URL 与 anon key。

create extension if not exists pgcrypto;

create or replace function public.generate_secret_key()
returns text
language plpgsql
as $$
declare
  chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  key text := '';
  i int := 0;
begin
  for i in 1..8 loop
    key := key || substr(chars, 1 + floor(random() * length(chars))::int, 1);
  end loop;
  return key;
end;
$$;

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  qq text not null,
  is_anonymous boolean not null default true,
  display_name text not null,
  challenge_items text[] not null,
  message text,
  secret_key text not null unique default public.generate_secret_key(),
  status text not null default 'pending',
  result_text text,
  rejection_reason text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  constraint qq_basic_check check (qq ~ '^[0-9]{5,15}$'),
  constraint display_name_check check (char_length(display_name) between 1 and 80),
  constraint challenge_items_check check (
    array_length(challenge_items, 1) between 1 and 4
    and challenge_items <@ array['Tap','Hold','Flick','Drag']::text[]
  ),
  constraint status_check check (status in ('pending', 'approved', 'rejected'))
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.registrations enable row level security;
alter table public.admins enable row level security;

-- 清理旧策略，便于重复执行脚本。
drop policy if exists "admins can read registrations" on public.registrations;
drop policy if exists "admins can update registrations" on public.registrations;
drop policy if exists "admins can read admins" on public.admins;

create policy "admins can read registrations"
on public.registrations
for select
to authenticated
using (
  exists (
    select 1 from public.admins a
    where a.user_id = auth.uid()
  )
);

create policy "admins can update registrations"
on public.registrations
for update
to authenticated
using (
  exists (
    select 1 from public.admins a
    where a.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admins a
    where a.user_id = auth.uid()
  )
);

create policy "admins can read admins"
on public.admins
for select
to authenticated
using (user_id = auth.uid());

-- 不给匿名用户直接读写表，只开放受控 RPC。
revoke all on table public.registrations from anon;
revoke all on table public.admins from anon;
grant select, update on table public.registrations to authenticated;
grant select on table public.admins to authenticated;

create or replace function public.submit_registration(
  p_qq text,
  p_is_anonymous boolean,
  p_display_name text,
  p_challenge_items text[],
  p_message text default null
)
returns table(secret_key text, created_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_items text[];
  new_key text;
  inserted_created_at timestamptz;
begin
  if p_qq is null or trim(p_qq) !~ '^[0-9]{5,15}$' then
    raise exception 'QQ号格式不正确，应为 5-15 位数字';
  end if;

  if p_display_name is null or char_length(trim(p_display_name)) < 1 or char_length(trim(p_display_name)) > 80 then
    raise exception '参赛名称不能为空，且不能超过 80 字符';
  end if;

  select array_agg(distinct item order by item)
  into normalized_items
  from unnest(p_challenge_items) as item
  where item in ('Tap','Hold','Flick','Drag');

  if normalized_items is null or array_length(normalized_items, 1) < 1 then
    raise exception '请至少选择一个挑战项目';
  end if;

  loop
    new_key := public.generate_secret_key();
    exit when not exists (select 1 from public.registrations r where r.secret_key = new_key);
  end loop;

  insert into public.registrations (
    qq,
    is_anonymous,
    display_name,
    challenge_items,
    message,
    secret_key
  )
  values (
    trim(p_qq),
    coalesce(p_is_anonymous, true),
    trim(p_display_name),
    normalized_items,
    nullif(trim(coalesce(p_message, '')), ''),
    new_key
  )
  returning registrations.created_at into inserted_created_at;

  return query select new_key, inserted_created_at;
end;
$$;

create or replace function public.public_lookup(p_secret_key text)
returns table(
  status text,
  qq text,
  is_anonymous boolean,
  display_name text,
  challenge_items text[],
  message text,
  rejection_reason text,
  result_text text,
  created_at timestamptz,
  reviewed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    r.status,
    case when r.status = 'approved' then r.qq else null end as qq,
    case when r.status = 'approved' then r.is_anonymous else null end as is_anonymous,
    case when r.status = 'approved' then r.display_name else null end as display_name,
    case when r.status = 'approved' then r.challenge_items else null end as challenge_items,
    case when r.status = 'approved' then r.message else null end as message,
    case when r.status = 'rejected' then r.rejection_reason else null end as rejection_reason,
    case when r.status = 'approved' then r.result_text else null end as result_text,
    r.created_at,
    r.reviewed_at
  from public.registrations r
  where r.secret_key = upper(trim(p_secret_key))
  limit 1;
$$;

revoke all on function public.submit_registration(text, boolean, text, text[], text) from public;
revoke all on function public.public_lookup(text) from public;

grant execute on function public.submit_registration(text, boolean, text, text[], text) to anon;
grant execute on function public.submit_registration(text, boolean, text, text[], text) to authenticated;
grant execute on function public.public_lookup(text) to anon;
grant execute on function public.public_lookup(text) to authenticated;

comment on table public.registrations is 'Phigros 自制谱面比赛报名、审核与随机挑战结果。';
comment on function public.submit_registration is '公开报名入口：校验字段、生成唯一密钥并返回给选手。';
comment on function public.public_lookup is '公开密钥查询入口：仅按密钥返回允许公开的字段，防止枚举选手 QQ。';
